import type { Metadata } from "next";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import { SERVER_API_URL } from "../constants";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import { lessThanExpiryDate } from "@/lib/utils";


export const metadata: Metadata = {
  title: "RSR Global CV",
  description: "Generated by create next app",
};

export async function getData() {
  const cookiesStore = cookies();
  const access = cookiesStore.get("access");

  // console.log(access);
  if (!access) {
    return null;
  }
  const res = await fetch(`${SERVER_API_URL}/users/me`, {
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${access?.value}`,
    },
    next:{
      tags:['User']
    }
  });

  if (!res.ok) {
    console.log("error");
  }

  if (res.status === 401) {
    redirect ('/login');
  }
  if (res.status !== 200) {
    return null;
  }



  const user = await res.json();
  console.log(user);
  
  if(user.expiry_date && !lessThanExpiryDate(user.expiry_date)){
    redirect ('/payment/renew');
  }

  return user;
}

type Data = User | null;


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user:Data = await getData();
  return (<>
        <Navbar user={user}/>
        {children}
        <Footer />
  </>
     
  );
}
