import type { Metadata } from "next";
import { Inter , Roboto} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import { SERVER_API_URL } from "./constants";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });
export const roboto = Roboto({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});
export const metadata: Metadata = {
  title: "RSR Global CV",
  description: "Generated by create next app",
};

export async function getData() {
  const cookiesStore = cookies();
  const access = cookiesStore.get("access");

  console.log(access);
  if (!access) {
    return null;
  }
  const res = await fetch(`${SERVER_API_URL}/users/me`, {
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${access?.value}`,
    },
    next:{
      tags:['User']
    }
  });

  if (!res.ok) {
    console.log("error");
  }

  if (res.status === 401) {
    return null;
  }

  const user = await res.json();
  console.log(user);

  return user;
}

type Data = User | null;

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user:Data = await getData();
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Navbar user={user}/>
        {children}
        <Footer />
      </body>
    </html>
  );
}
